FROM public.ecr.aws/docker/library/nginx:1.30-alpine@sha256:02b1b2a0445514891a14aa371845f6085d5d9d10d385b30d6aad606a50a29a05

RUN apk add --no-cache libcrypto3=3.5.8-r0 libssl3=3.5.8-r0

COPY nginx.rc.conf /etc/nginx/conf.d/default.conf

HEALTHCHECK --interval=15s --timeout=5s --start-period=10s --retries=3 \
    CMD wget -qO- http://127.0.0.1/health || exit 1
